export type Role = {
  role: string;
  group: string;
  accessLevel: string;
  members: number;
  permissionSets: string[];
  lastReview: string;
  owner: string;
  status: "Active" | "Needs review";
};

export const roles: Role[] = [
  {
    role: "Owner",
    group: "Needs review",
    accessLevel: "Full",
    members: 2,
    permissionSets: ["Members", "Settings", "Billing", "Reports", "Integrations", "Audit Logs"],
    lastReview: "Apr 12, 2025",
    owner: "System",
    status: "Needs review",
  },
  {
    role: "Admin",
    group: "Needs review",
    accessLevel: "Full",
    members: 5,
    permissionSets: ["Members", "Settings", "Reports", "Billing", "Integrations"],
    lastReview: "Apr 15, 2025",
    owner: "Jane Doe",
    status: "Needs review",
  },
  {
    role: "Manager",
    group: "Needs review",
    accessLevel: "Scoped",
    members: 12,
    permissionSets: ["Members", "Reports", "Projects", "Tasks"],
    lastReview: "Apr 18, 2025",
    owner: "Jane Doe",
    status: "Needs review",
  },
  {
    role: "Support",
    group: "System roles",
    accessLevel: "Scoped",
    members: 8,
    permissionSets: ["Members", "Tickets", "Reports", "Knowledge Base"],
    lastReview: "May 1, 2025",
    owner: "System",
    status: "Active",
  },
  {
    role: "Analyst",
    group: "System roles",
    accessLevel: "Scoped",
    members: 6,
    permissionSets: ["Reports", "Analytics", "Dashboards", "Exports"],
    lastReview: "May 5, 2025",
    owner: "System",
    status: "Active",
  },
  {
    role: "Guest",
    group: "System roles",
    accessLevel: "Read only",
    members: 14,
    permissionSets: ["Reports", "Dashboards"],
    lastReview: "May 6, 2025",
    owner: "System",
    status: "Active",
  },
  {
    role: "Service",
    group: "System roles",
    accessLevel: "API access",
    members: 3,
    permissionSets: ["Integrations", "API Keys", "Webhooks", "Logs"],
    lastReview: "Apr 22, 2025",
    owner: "System",
    status: "Active",
  },
  {
    role: "Billing",
    group: "Custom roles",
    accessLevel: "Scoped",
    members: 3,
    permissionSets: ["Billing", "Invoices", "Payments", "Reports"],
    lastReview: "Apr 28, 2025",
    owner: "Alex Kim",
    status: "Active",
  },
  {
    role: "Marketing",
    group: "Custom roles",
    accessLevel: "Scoped",
    members: 9,
    permissionSets: ["Members", "Reports", "Campaigns", "Analytics", "Exports"],
    lastReview: "May 2, 2025",
    owner: "Alex Kim",
    status: "Active",
  },
  {
    role: "Developer",
    group: "Custom roles",
    accessLevel: "Scoped",
    members: 10,
    permissionSets: ["Repos", "Deployments", "Settings", "API Keys", "Logs"],
    lastReview: "May 3, 2025",
    owner: "Chris Lee",
    status: "Active",
  },
  {
    role: "Project Lead",
    group: "Custom roles",
    accessLevel: "Scoped",
    members: 7,
    permissionSets: ["Projects", "Tasks", "Reports", "Members", "Settings"],
    lastReview: "Apr 30, 2025",
    owner: "Chris Lee",
    status: "Active",
  },
  {
    role: "Finance Viewer",
    group: "Custom roles",
    accessLevel: "Read only",
    members: 4,
    permissionSets: ["Billing", "Reports", "Invoices", "Dashboards"],
    lastReview: "May 7, 2025",
    owner: "Jane Doe",
    status: "Active",
  },
];
